<!-- Bootstrap JS -->
<script src="JS/jquery.slim.min.js"></script>
<script src="JS/popper.min.js"></script>
<script src="JS/bootstrap.min.js"></script>
<script src="JS/FA-all.js"></script>

<!-- Custom JS -->
<script src="JS/custom_script.js"></script>

<!-- UPPER Bootstrap JS -->
<script src="../JS/jquery.slim.min.js"></script>
<script src="../JS/popper.min.js"></script>
<script src="../JS/bootstrap.min.js"></script>
<script src="../JS/FA-all.js"></script>

<!-- UPPER Custom JS -->
<script src="../JS/custom_script.js"></script>